### PR TITLE
Fixes #20. Implements the color chooser in GUI.

### LINKED ISSUE #20: Choose color for the plot
Use radiobutton to design the color chooser. list simple colors like
red, blue, cyan, black, green and one text box next to option to enter custom hex value for color.

Attempt after #14  is solved.

### PR DESCRIPTION
**Pull request by kvaghel1**
The specified color can be chosen from the radio button.A different color can be also input using the textbox. The gui can be executed using "python gui_main.py"

### CODE REVIEW

**Comment by Aniq55** [comment]
we don't need the files in .temp
I think its included in the gitignore already.

**Comment by Aniq55** [comment]
@kvaghel1 could you please post a screenshot of the gui here?

**Comment by djmgit** [comment]
graph

@kvaghel1 thanks a lot for working on this, nice work :)
@Aniq55 I am posting here the screenshot on behalf of @kvaghel1 just to speed up the process. Will it not be better to use a dropdown instead of a list of radio buttons? A dropdown/spinner will take up less space than this list of radio buttons. What are your views on this?

**Comment by Aniq55** [comment]
@kvaghel1 nice work. @djmgit support your idea of drop down. You should merge this, I guess. Create a new issue for drop down menu.
For dropdown:
```
color 1
color 2
...
color N
other
```
thn there'll be a text field for entering the `other` color. and then a `select` button next to the drop down bar.

**Comment by djmgit** [comment]
@Aniq55 okay, great!, merging this.
@kvaghel1 From next time please squash your commits into one, there should be one commit per pull request :)

**Pull request merged**
